# Generated by Django 4.1.4 on 2022-12-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0002_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('inv', 'inv'), ('buss', 'buss')], max_length=12),
        ),
    ]
