# Generated by Django 4.1.4 on 2022-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0004_bussinesman_compnany_image_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compnany',
            old_name='birth_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='compnany',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='compnany',
            name='surname',
        ),
        migrations.AlterField(
            model_name='bussinesman',
            name='role',
            field=models.CharField(default='buss', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='compnany',
            name='role',
            field=models.CharField(default='com', editable=False, max_length=12),
        ),
    ]
