# Generated by Django 4.1.4 on 2022-12-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0005_rename_birth_date_compnany_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesman',
            name='avatar',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='offer_start.image'),
        ),
        migrations.AlterField(
            model_name='compnany',
            name='avatar',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='offer_start.image'),
        ),
    ]
