# Generated by Django 4.1.4 on 2022-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0006_alter_bussinesman_avatar_alter_compnany_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussinesman',
            old_name='avatar',
            new_name='avatar_id',
        ),
        migrations.RenameField(
            model_name='compnany',
            old_name='avatar',
            new_name='avatar_id',
        ),
    ]
