# Generated by Django 4.1.4 on 2022-12-19 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer_start', '0007_rename_avatar_bussinesman_avatar_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compnany',
            new_name='Company',
        ),
    ]
