# Generated by Django 4.1.4 on 2022-12-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0008_rename_compnany_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinesman',
            name='avatar_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avatar_id',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
