# Generated by Django 4.1.4 on 2022-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0010_image_bussinesman_avatar_id_company_avatar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinesman',
            name='avatar_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avatar_id',
        ),
        migrations.AddField(
            model_name='bussinesman',
            name='avatar',
            field=models.ImageField(null=True, upload_to='picture/avatar/'),
        ),
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ImageField(null=True, upload_to='picture/avatar/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
