# Generated by Django 4.1.4 on 2022-12-15 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 11, 7, 48, 554059)),
        ),
    ]
