# Generated by Django 4.1.4 on 2022-12-15 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_defaultuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 11, 9, 3, 386482)),
        ),
    ]
