# Generated by Django 4.1.4 on 2022-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_defaultuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
