# Generated by Django 4.1.4 on 2022-12-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_defaultuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('call_number', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(null=True, upload_to='picture/avatar/')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('surname', models.CharField(blank=True, max_length=60)),
                ('birth_date', models.DateField(blank=True)),
                ('locate', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('sub_industry', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('gender', models.CharField(blank=True, max_length=12)),
                ('role', models.CharField(default='buss', editable=False, max_length=12)),
            ],
            options={
                'verbose_name': 'Предприниматель',
                'verbose_name_plural': 'Предприниматели',
            },
        ),
    ]
